name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: sharepress-deploy
      uses: ./
      env:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        TARGET_REPO: share-framework/sharepress
        TARGET_BRANCH: publish
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: /
        COMMIT_MESSAGE: Auto deploy from Github Actions
        #CNAME: https://www.andotorg.com