name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        TARGET_REPO: share-framework/sharepress
        TARGET_BRANCH: publish
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: /public
        COMMIT_MESSAGE: Auto deploy from Github Actions
        #CNAME: https://www.andotorg.com
