name: Build and Deploy
on: [push]
jobs:
  run:
    name: build-and-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2.3.4

    - name: sharepress-deploy
      uses: share-framework/sharepress@master
      env:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        TARGET_REPO: share-framework/sharepress
        TARGET_BRANCH: publish
        BUILD_SCRIPT: yarn && yarn build
        BUILD_DIR: docs/.vuepress/dist
        COMMIT_MESSAGE: Auto deploy from Github Actions
        #CNAME: https://www.andotorg.com